version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 127.0.0.1:5432:${DB_PORT}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
